### ISSUE TITLE
Support for changing tag and passing HTML options

### ISSUE THREAD

**Issue by CyberPunkCodes** [powerkernel/yii2-fontawesome#2]
There should be support for changing the tag. `i` isn't the only tag that can be used.

```
<div class="fa fa-user"></div>
```

There should be the option to pass html options so you could generate the following:

```
<i class="fa fa-user" aria-hidden="true" id="xyz"></i>
```

There are many other `fa` options, for size, fixed, width, lists, etc. As shown here: http://fontawesome.io/examples/

I also think the class names should be `FontAwesome` not `Fontawesome`.

**Comment by harrytang** [comment]
Resolved by commit https://github.com/powerkernel/yii2-fontawesome/commit/e394c335ff6e577655b57c21466aa1792973e23e
